-- MySQL Script generated by MySQL Workbench
-- Fri Apr  7 09:37:38 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema externatic
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema externatic
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `externatic` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `externatic` ;

-- -----------------------------------------------------
-- Table `externatic`.`candidat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `externatic`.`candidat` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NOT NULL,
  `Prenom` VARCHAR(45) NOT NULL,
  `Date_naissance` DATE NOT NULL,
  `Adresse_rue` VARCHAR(45) NOT NULL,
  `Adresse_ville` VARCHAR(45) NOT NULL,
  `Adresse_CP` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Telephone` VARCHAR(45) NOT NULL,
  `Mot_de_passe` VARCHAR(45) NOT NULL,
  `En_recherche` TINYINT NOT NULL,
  `Photo` VARCHAR(45) NULL DEFAULT NULL,
  `CV` VARCHAR(45) NULL DEFAULT NULL,
  `Pref_contact` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `externatic`.`consultant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `externatic`.`consultant` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NOT NULL,
  `Prenom` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Telephone` VARCHAR(45) NOT NULL,
  `Date_naissance` DATE NOT NULL,
  `Mot_de_passe` VARCHAR(45) NOT NULL,
  `Adresse_rue` VARCHAR(45) NOT NULL,
  `Adresse_ville` VARCHAR(45) NOT NULL,
  `Adresse_CP` VARCHAR(45) NOT NULL,
  `Photo` VARCHAR(45) NULL DEFAULT NULL,
  `Super_Admin` TINYINT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `externatic`.`contrat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `externatic`.`contrat` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Type` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `externatic`.`poste`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `externatic`.`poste` (
  `id` INT NOT NULL,
  `Nom` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `externatic`.`entreprise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `externatic`.`entreprise` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Num_siret` VARCHAR(60) NOT NULL,
  `Nom` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Tel` VARCHAR(45) NOT NULL,
  `Mot_de_passe` VARCHAR(45) NOT NULL,
  `Valide` TINYINT NOT NULL,
  `Logo` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `externatic`.`recruteur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `externatic`.`recruteur` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Entreprise_id` INT NOT NULL,
  `Nom` VARCHAR(45) NOT NULL,
  `Prenom` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Telephone` VARCHAR(45) NOT NULL,
  `Date_naissance` DATE NOT NULL,
  `Mot_de_passe` VARCHAR(45) NOT NULL,
  `Adresse_rue` VARCHAR(45) NOT NULL,
  `Adresse_ville` VARCHAR(45) NOT NULL,
  `Adresse_CP` VARCHAR(45) NOT NULL,
  `Valide` TINYINT NOT NULL,
  `Photo` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `Entreprise_id`),
  INDEX `fk_Recruteur_Entreprise1_idx` (`Entreprise_id` ASC) VISIBLE,
  CONSTRAINT `fk_Recruteur_Entreprise1`
    FOREIGN KEY (`Entreprise_id`)
    REFERENCES `externatic`.`entreprise` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `externatic`.`region`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `externatic`.`region` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `externatic`.`ville`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `externatic`.`ville` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Region_id` INT NOT NULL,
  `Nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `Region_id`),
  INDEX `fk_Ville_Region1_idx` (`Region_id` ASC) VISIBLE,
  CONSTRAINT `fk_Ville_Region1`
    FOREIGN KEY (`Region_id`)
    REFERENCES `externatic`.`region` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `externatic`.`offre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `externatic`.`offre` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Consultant_id` INT NOT NULL,
  `Recruteur_id` INT NOT NULL,
  `Contrat_id` INT NOT NULL,
  `Poste_id` INT NOT NULL,
  `Ville_id` INT NOT NULL,
  `Salaire` VARCHAR(45) NOT NULL,
  `Teletravail` INT NOT NULL,
  `Valide` TINYINT NOT NULL,
  `Photo_equipe` VARCHAR(45) NOT NULL,
  `Presentation_offre` VARCHAR(1000) NOT NULL,
  `Profil_recherche` VARCHAR(1000) NOT NULL,
  `Process_recrutement` VARCHAR(1000) NOT NULL,
  `Nb_collaborateur` VARCHAR(45) NULL DEFAULT NULL,
  `Poste_detail` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `Recruteur_id`, `Contrat_id`, `Poste_id`, `Ville_id`, `Consultant_id`),
  INDEX `fk_Offre_Consultant1_idx` (`Consultant_id` ASC) VISIBLE,
  INDEX `fk_Offre_Recruteur1_idx` (`Recruteur_id` ASC) VISIBLE,
  INDEX `fk_Offre_Contrat1_idx` (`Contrat_id` ASC) VISIBLE,
  INDEX `fk_Offre_Poste1_idx` (`Poste_id` ASC) VISIBLE,
  INDEX `fk_Offre_Ville1_idx` (`Ville_id` ASC) VISIBLE,
  CONSTRAINT `fk_Offre_Consultant1`
    FOREIGN KEY (`Consultant_id`)
    REFERENCES `externatic`.`consultant` (`id`),
  CONSTRAINT `fk_Offre_Contrat1`
    FOREIGN KEY (`Contrat_id`)
    REFERENCES `externatic`.`contrat` (`id`),
  CONSTRAINT `fk_Offre_Poste1`
    FOREIGN KEY (`Poste_id`)
    REFERENCES `externatic`.`poste` (`id`),
  CONSTRAINT `fk_Offre_Recruteur1`
    FOREIGN KEY (`Recruteur_id`)
    REFERENCES `externatic`.`recruteur` (`id`),
  CONSTRAINT `fk_Offre_Ville1`
    FOREIGN KEY (`Ville_id`)
    REFERENCES `externatic`.`ville` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `externatic`.`candidat_offre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `externatic`.`candidat_offre` (
  `Candidat_id` INT NOT NULL AUTO_INCREMENT,
  `Offre_id` INT NOT NULL,
  PRIMARY KEY (`Candidat_id`, `Offre_id`),
  INDEX `fk_Candidat_has_Offre_Offre1_idx` (`Offre_id` ASC) VISIBLE,
  INDEX `fk_Candidat_has_Offre_Candidat1_idx` (`Candidat_id` ASC) VISIBLE,
  CONSTRAINT `fk_Candidat_has_Offre_Candidat1`
    FOREIGN KEY (`Candidat_id`)
    REFERENCES `externatic`.`candidat` (`id`),
  CONSTRAINT `fk_Candidat_has_Offre_Offre1`
    FOREIGN KEY (`Offre_id`)
    REFERENCES `externatic`.`offre` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `externatic`.`filtre_candidat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `externatic`.`filtre_candidat` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Poste_id` INT NOT NULL,
  `Contrat_id` INT NOT NULL,
  `Ville_id` INT NOT NULL,
  `Candidat_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Poste_id`, `Contrat_id`, `Ville_id`, `Candidat_id`),
  INDEX `fk_Filtre_candidat_Poste1_idx` (`Poste_id` ASC) VISIBLE,
  INDEX `fk_Filtre_candidat_Contrat1_idx` (`Contrat_id` ASC) VISIBLE,
  INDEX `fk_Filtre_candidat_Ville1_idx` (`Ville_id` ASC) VISIBLE,
  INDEX `fk_Filtre_candidat_Candidat1_idx` (`Candidat_id` ASC) VISIBLE,
  CONSTRAINT `fk_Filtre_candidat_Candidat1`
    FOREIGN KEY (`Candidat_id`)
    REFERENCES `externatic`.`candidat` (`id`),
  CONSTRAINT `fk_Filtre_candidat_Contrat1`
    FOREIGN KEY (`Contrat_id`)
    REFERENCES `externatic`.`contrat` (`id`),
  CONSTRAINT `fk_Filtre_candidat_Poste1`
    FOREIGN KEY (`Poste_id`)
    REFERENCES `externatic`.`poste` (`id`),
  CONSTRAINT `fk_Filtre_candidat_Ville1`
    FOREIGN KEY (`Ville_id`)
    REFERENCES `externatic`.`ville` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `externatic`.`message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `externatic`.`message` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Personne_1` INT NULL DEFAULT NULL,
  `Personne_1_REF` VARCHAR(45) NOT NULL,
  `Personne_2` INT NOT NULL,
  `Personne_2_REF` VARCHAR(45) NOT NULL,
  `Date` DATE NOT NULL,
  `Heure` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `externatic`.`notification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `externatic`.`notification` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `externatic`.`rdv`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `externatic`.`rdv` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Heure_debut` DATETIME NOT NULL,
  `Heure_fin` DATETIME NOT NULL,
  `Personne_1` INT NOT NULL,
  `Personne_1_REF` VARCHAR(45) NOT NULL,
  `Personne_2` INT NOT NULL,
  `Personne_2_REF` VARCHAR(45) NOT NULL,
  `Date` DATE NOT NULL,
  `Accepte` TINYINT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


-- Ajout entreprise (benjamin 07/04)
INSERT INTO entreprise (Num_siret, Nom, Email, Tel, Mot_de_passe, Valide, Logo)
VALUES ('12345678901234', 'Fake Company', 'fakecompany@example.com', '0123456789', 'motdepasse', 1, NULL);

--Ajout recruteurs (benjamin 07/04)
INSERT INTO recruteur (Entreprise_id, Nom, Prenom, Email, Telephone, Date_naissance, Mot_de_passe, Adresse_rue, Adresse_ville, Adresse_CP, Valide, Photo)
VALUES (1, 'Doe', 'John', 'john.doe@example.com', '1234567890', '1990-01-01', '1234', '123 Rue du Recrutement', 'VilleRecrute', '12345', 1, NULL);

INSERT INTO recruteur (Entreprise_id, Nom, Prenom, Email, Telephone, Date_naissance, Mot_de_passe, Adresse_rue, Adresse_ville, Adresse_CP, Valide, Photo)
VALUES (1, 'Smith', 'Jane', 'jane.smith@example.com', '9876543210', '1985-05-10', '5678', '456 Avenue du Recrutement', 'VilleRecrute', '67890', 0, NULL);

INSERT INTO recruteur (Entreprise_id, Nom, Prenom, Email, Telephone, Date_naissance, Mot_de_passe, Adresse_rue, Adresse_ville, Adresse_CP, Valide, Photo)
VALUES (1, 'Brown', 'Mike', 'mike.brown@example.com', '4567890123', '1995-07-15', '9876', '789 Boulevard du Recrutement', 'VilleRecrute', '23456', 1, NULL);

INSERT INTO recruteur (Entreprise_id, Nom, Prenom, Email, Telephone, Date_naissance, Mot_de_passe, Adresse_rue, Adresse_ville, Adresse_CP, Valide, Photo)
VALUES (1, 'Smith', 'Jane', 'jane.smith@example.com', '9876543210', '1985-05-10', '5678', '456 Avenue du Recrutement', 'VilleRecrute', '67890', 0, NULL);

--Permet de mettre une valeur de 0 pour le champ valide, (benjamin 07/04)
ALTER TABLE recruteur MODIFY valide TINYINT(1) NOT NULL DEFAULT 0;